server:
  port: 8090
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 1048576000
      max-request-size: 1048576000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mystock?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&useOldAliasMetadataBehavior=true
    username: root
    password: 123123
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
logging:
  level:
    com:
      tanshiyang: debug